

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_app_development
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

test:
  <<: *default
  database: my_app_test
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
